
project:
  type: website
  output-dir: docs

website:
  title: "Megan Stefanowski"
  navbar:
   background: primary
   left:
     - href: index.qmd
       text: Home
     - aboutme.qmd
     - pilates.qmd
     - portfolio.qmd

format:
  html:
    theme: 
      light: journal
      dark: superhero
    css: styles.css
    
editor: visual

