
project:
  type: website
  output-dir: docs

website:
  title: "Megan Stefanowski"
  navbar:
   search: false
   background: primary
   left:
     - href: index.qmd
       text: Home
     - aboutme.qmd
     - pilates.qmd
     - portfolio.qmd
   right: 
     - "Toggle to dark mode"

format:
  html:
      include:
      in_header: styles.css
    in-header: 
    theme: 
      light: journal
      dark: superhero
    css: styles.css
    
editor: visual

