
project:
  type: website
  output-dir: docs

website:
  title: "Megan Stefanowski"
  navbar:
   background: primary
   logo: media/heart.png
   left:
     - href: index.qmd
       text: Home
     - aboutme.qmd
     - pilates.qmd
     - portfolio.qmd
  search: false

format:
  html:
   theme: 
      - cosmo
      - styles.scss
   mainfont: Roboto Slab
   toc: false
   page-layout: full
      
  
editor: visual

