project:
  type: website
  output-dir: docs
  

website:
  title: "Megan Stefanowski"
  navbar:
  background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - aboutme.qmd 
      - pilates.qmd

format:
  html:
    theme: 
      light: journal
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full 

editor: visual

